// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id" gorm:"primary_key"`
	Text string `json:"text" gorm:"not null"`
	Done bool   `json:"done" gorm:"default false" `
	User *User  `json:"user" gorm:"foreignkey:ID;constraint:OnDelete:CASCADE;"`
}

type User struct {
	ID   string `json:"id" gorm:"primary_key"`
	Name string `json:"name"`
}
